version: '3.8'

services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PWD}
    command: -p ${POSTGRES_PORT}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - pg:/var/lib/postgresql/data

  redis:
    image: redis:7.0.5
    expose:
      - ${REDIS_PORT}
    command: redis-server --port ${REDIS_PORT}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}

  backend:
    container_name: nestjs-backend
    build:
      context: ./
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
    ports:
      - ${PORT}:${PORT}



volumes:
  redis:
    driver: local
  pg:
    driver: local
